#!/bin/bash

# Función para verificar e instalar GUM si no está presente
instalar_gum() {
    if ! command -v gum &> /dev/null; then
        echo "GUM no está instalado. Instalándolo ahora..."
        sudo pacman -S gum
    fi
}

# Función para mostrar la ayuda
mostrar_ayuda() {
    gum style --border normal --margin "1" --padding "1" --border-foreground 212 "Uso: $0 [ruta_del_archivo]

Este script mueve un archivo a la carpeta ~/.dotfiles y crea un enlace simbólico en la ubicación original.

Opciones:
  --help    Muestra esta ayuda y sale"
}

# Función para mover el archivo y crear el enlace simbólico
mover_y_enlazar() {
    local archivo_origen="$1"
    local nombre_archivo=$(basename "$archivo_origen")
    local carpeta_origen=$(dirname "$archivo_origen")
    local carpeta_dotfiles="$HOME/.dotfiles/$carpeta_origen"

    # Crear la carpeta ~/.dotfiles si no existe
    mkdir -p "$carpeta_dotfiles"

    # Mover el archivo a la nueva ubicación
    mv "$archivo_origen" "$carpeta_dotfiles"

    # Crear un enlace simbólico desde la nueva ubicación a la carpeta de origen
    ln -s "$carpeta_dotfiles/$nombre_archivo" "$carpeta_origen/$nombre_archivo"

    # Asignar permisos necesarios
    chmod 755 "$carpeta_dotfiles"
    chmod 644 "$carpeta_dotfiles/$nombre_archivo"

    gum style --foreground 10 "Archivo movido y enlace simbólico creado exitosamente."
}

# Verifica si se proporcionaron los argumentos necesarios o si se solicitó ayuda
if [ "$#" -ne 1 ]; then
    if [ "$1" == "--help" ]; then
        mostrar_ayuda
        exit 0
    else
        archivo_origen=$(gum input --placeholder "Ingrese la ruta del archivo")
    fi
else
    archivo_origen="$1"
fi

# Ejecutar funciones
instalar_gum
mover_y_enlazar "$archivo_origen"