#!/bin/bash

clear
# Guardar el valor original de HOME
ORIGINAL_HOME=$HOME

# Verificar si el script se está ejecutando con sudo
function check_sudo() {
  if [ "$EUID" -ne 0 ]; then
    echo -e "\e[31mEste script necesita privilegios de sudo. Solicitando sudo...\e[0m"
    exec sudo HOME=$ORIGINAL_HOME bash "$0" "$@"
    echo "Checking HOME $HOME and $ORIGINAL_HOME"
    read "" > /dev/null
  fi
}

# Verificar si gum está instalado
function check_gum() {
  if ! command -v gum &> /dev/null; then
    echo "gum no está instalado. Instalando gum..."
    pacman -S gum --noconfirm
  fi
}

# Función para limpiar la pantalla
clear_screen() {
    clear
}

# Función para instalar los paquetes necesarios
install_packages() {
    pacman -Sy --noconfirm hyprland sddm kitty
    systemctl enable sddm
    systemctl start sddm
}

# Función para cambiar el layout del teclado
change_keyboard_layout() {
    local layout=$(gum choose --limit 1 $(awk '/! layout/ {flag=1; next} /! variant/ {flag=0} flag {print $1}' /usr/share/X11/xkb/rules/base.lst))
    
    # Verificar si el layout seleccionado es válido
    if localectl list-x11-keymap-layouts | grep -q "^$layout$"; then
        sed -i "s/kb_layout = .*/kb_layout = $layout/" "$ORIGINAL_HOME/.config/hypr/hyprland.conf"
        echo "Layout del teclado cambiado a $layout."
    else
        echo "Layout del teclado no válido: $layout. No se realizaron cambios."
    fi
}

# Función para configurar autologin en sddm
configure_autologin() {
    local user=$(gum choose --limit 1 $(awk -F: '{ print $1 }' /etc/passwd))
    mkdir -p /etc/sddm.conf.d/
    tee /etc/sddm.conf.d/autologin.conf > /dev/null <<EOF
[Autologin]
User=$user
Session=hyprland
EOF
}

# Función para configurar hyprland.conf
setup_hyprland_config() {
    local script_dir=$(dirname "$0")
    local config_path="$ORIGINAL_HOME/.config/hypr/hyprland.conf"
    local source_config="$script_dir/hyprland.conf"
    
    if [ ! -f "$source_config" ]; then
        echo "El archivo fuente hyprland.conf no existe en $source_config. Por favor, verifica la ruta."
        return 1
    fi

    if [ ! -f "$config_path" ]; then
        echo "El archivo hyprland.conf no existe. Copiando archivo..."
        mkdir -p "$(dirname "$config_path")"
        cp "$source_config" "$config_path"
    fi
    
    if grep -q 'autogenerated = 1' "$config_path"; then
        sed -i '1,9d' "$config_path"
    else
        echo "El archivo hyprland.conf no contiene 'autogenerated = 1'. No se realizarán cambios."
    fi

    chown -R "$SUDO_USER:$SUDO_USER" "$ORIGINAL_HOME/.config/hypr"
    chmod -R 755 "$ORIGINAL_HOME/.config/hypr"
    echo "Configuración de hyprland completada."
}

# Función para instalar Waybar
install_waybar() {
    local config_path="$1"
    if gum confirm "¿Deseas instalar Waybar?" --affirmative "Sí" --negative "No"; then
        pacman -Sy --noconfirm waybar otf-font-awesome
        echo "Waybar ha sido instalado."
        # Eliminar la línea siguiente a '# exec-once = waybar &' y agregar 'exec-once = waybar &'
        if grep -q '# exec-once = waybar &' "$config_path" 2>/dev/null; then
            sed -i '/# exec-once = waybar &/{n;d}' "$config_path"
            sed -i '/# exec-once = waybar &/a exec-once = waybar &' "$config_path"
        fi
    else
        echo "Instalación de Waybar cancelada."
    fi
}

# Función para instalar Rofi con configuración base
install_rofi() {
    if gum confirm "¿Deseas instalar Rofi?" --affirmative "Sí" --negative "No"; then
        pacman -Sy --noconfirm rofi
        echo "Rofi ha sido instalado."
        local rofi_config_dir="$ORIGINAL_HOME/.config/rofi"
        mkdir -p "$rofi_config_dir"
        tee "$rofi_config_dir/config.rasi" > /dev/null <<EOF
configuration {
    modi: "drun,run";
    show-icons: true;
}
@theme "default"
EOF
        chown -R "$SUDO_USER:$SUDO_USER" "$rofi_config_dir"
        chmod -R 755 "$rofi_config_dir"
        echo "Configuración base de Rofi ha sido creada."
    else
        echo "Instalación de Rofi cancelada."
    fi
}

# Verificar si el usuario es sudo
check_sudo

# Verificar si gum está instalado
check_gum

# Limpiar la pantalla
clear_screen

# Preguntar si se desea instalar los paquetes
if gum confirm "¿Deseas instalar Hyprland, SDDM y Kitty?" --affirmative "Sí" --negative "No"; then
    install_packages

    # Configurar hyprland.conf
    setup_hyprland_config

    # Definir config_path
    config_path="$ORIGINAL_HOME/.config/hypr/hyprland.conf"

    # Preguntar si se desea cambiar el layout del teclado
    if gum confirm "¿Deseas cambiar el layout del teclado?" --affirmative "Sí" --negative "No"; then
        change_keyboard_layout
    fi

    # Preguntar si se desea configurar autologin en sddm
    if gum confirm "¿Deseas configurar autologin en SDDM?" --affirmative "Sí" --negative "No"; then
        configure_autologin
    fi

    # Preguntar si se desea instalar Waybar
    install_waybar "$config_path"

    # Preguntar si se desea instalar Rofi
    install_rofi

    if gum confirm "¿Desea reiniciar Display Manager?" --affirmative "Sí" --negative "No"; then
        systemctl restart display-manager
    fi
fi


